# Generated by Django 5.2.5 on 2025-08-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempmaildata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
